View
tonnytech/blog_webiste pull request #6
Opened 2023-09-29 14:00 UTC by tonnytech

### Did the following in this pull request:

- Implement the design from the sneak peek wireframes.
- Use methods that I have created in the models.

2023-09-29 14:33 UTC, elisha2kyakpo1 requested changes
Hi 👋 @tonnytech, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description are good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.
👏 The app works as expected without errors, though some features are missing.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 14:33 UTC, elisha2kyakpo1 commented on app/views/users/show.html.erb
> +        <% end %>
- [ ] Kindly add basic CSS to the user show page to match the wireframe design. Your design is different from the wireframe.
- [ ] The "See all Posts" button doesn't work, I had to type the URL in the browser to see all the posts, Kindly fix this issue for an easy user experience.

![user-show](https://github.com/tonnytech/blog_webiste/assets/53124548/6b55ca65-e1bf-4c32-983e-461acadad72d)

![design](https://github.com/tonnytech/blog_webiste/assets/53124548/a7fba7c0-80f0-4766-9978-225203188532)

2023-09-29 14:33 UTC, elisha2kyakpo1 commented on app/views/posts/index.html.erb
> +                </div>
- [ ] Kindly make this page design to match the wireframe, observe the difference, and make changes.
- [ ] Note that this page should have a pagination button.

![posts](https://github.com/tonnytech/blog_webiste/assets/53124548/fa160634-e9aa-4b29-a529-b165e836dd87)


![wireframe](https://github.com/tonnytech/blog_webiste/assets/53124548/aa75dad6-4a75-4839-ab3d-79ef7372a07d)

2023-09-30 09:14 UTC, levy002 approved these changes
## Hello @tonnytech   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 
- You implemented the suggested changes :heavy_check_mark: 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 08:42 UTC, merged