Fix n+1
tonnytech/blog_webiste pull request #8
Opened 2023-10-06 09:57 UTC by tonnytech

### In this project, We did the following changes:
1. fix the n+1 problem:
     the image before:
     ![before](https://github.com/tonnytech/blog_webiste/assets/92226962/47f0d39c-3ef0-4e2d-9527-6ef9ce0a351f)
    The image of the after:
    ![after](https://github.com/tonnytech/blog_webiste/assets/92226962/1b7576ad-866a-476d-9aeb-b8a7ea617366)

2. Added tests for the views

2023-10-06 12:40 UTC, addod19 requested changes
## Hi @tonnytech and @BenM4k, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] README file is professional :fireworks: 
- [ ] N+1 query problem addressed :rocket: 
- [ ] All written test cases passed :100: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
**NOTE**: Optional but important
- [ ] This is an opportunity for the other coding partner to make some commits, we encourage equal collaboration. The next reviewer will take note of that hopefully


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 12:40 UTC, addod19 commented on spec/views/users/user_show_spec.rb
> +
- [ ] It would be better if we add the remaining test cases as seen in the requirements
![Screenshot from 2023-10-06 12-28-30](https://github.com/tonnytech/blog_webiste/assets/46388113/9a7bc832-da63-4912-85cf-b74514fa18b8)

2023-10-06 12:40 UTC, addod19 commented on spec/views/posts/posts_index_spec.rb
> +
- [ ] It would be better if we add the remaining test cases as seen in the requirements below
![Screenshot from 2023-10-06 12-30-06](https://github.com/tonnytech/blog_webiste/assets/46388113/f41b4c1b-9656-471e-9199-b5d22d8ab3e7)

2023-10-06 12:40 UTC, addod19 commented on spec/views/posts/post_show_spec.rb
> +  end
- [ ] In the test scenario, we are expected to test who wrote the post, kindly fix that accordingly

2023-10-06 12:40 UTC, addod19 commented on spec/views/posts/post_show_spec.rb
> +
- [ ] It would be better if we add the remaining test case as we have in the requirements
![Screenshot from 2023-10-06 12-32-39](https://github.com/tonnytech/blog_webiste/assets/46388113/56bb4640-d374-4ff2-9637-ef04f92bcc61)

2023-10-07 05:07 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @tonnytech and @BenM4k, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

✔️ You did well to add more tests as requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-07 05:51 UTC, merged